### ISSUE TITLE
ImportError No module named ssl_match_hostname on docker-inside-setup --auto-pull

### ISSUE THREAD

**Issue by rrebollo** [boon-code/docker-inside#15]
Any base dependency not mentioned in readme???

Here is the full trace:

docker-inside-setup --auto-pull
Traceback (most recent call last):
  File "/home/roly/.local/bin/docker-inside-setup", line 6, in <module>
    from dockerinside.setup.__init__ import setup_main
  File "/home/roly/.local/lib/python2.7/site-packages/dockerinside/__init__.py", line 9, in <module>
    import docker
  File "/home/roly/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/roly/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/roly/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/home/roly/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/roly/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/roly/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/roly/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/roly/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/home/roly/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/home/roly/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

Tried:
pip install backports.ssl-match-hostname

Getting:
Requirement already satisfied: backports.ssl-match-hostname in /home/roly/.local/lib/python2.7/site-packages (3.7.0.1)

**Comment by boon-code** [comment]
Hi, the package is written for Python 3 only. I have never checked what would be necessary to make it run using Python 2.
Is it necessary for you to run it using Python 2?

**Comment by rrebollo** [comment]
Should I use "pip3 install ..." instead on installation process????

**Comment by rrebollo** [comment]
Well, everything seems to be fine when installed with pip3. Maybe you could mention python 3 requirement on readme??? Anyway, thanks.

**Comment by boon-code** [comment]
Actually it should be visible on Pypi (category Python :: 3 :: only -> from setup.py); but you are right, mentioning it on the README wouldn't hurt.

**Comment by boon-code** [comment]
Has been added explicitly to README.md
